<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="75" started-at="2019-12-07T16:48:08Z" finished-at="2019-12-07T16:48:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="75" started-at="2019-12-07T16:48:08Z" finished-at="2019-12-07T16:48:08Z">
      <class name="com.test.ConsoleInputTest">
        <test-method status="FAIL" signature="enterLetter()[pri:0, instance:com.test.ConsoleInputTest@48eff760]" name="enterLetter" duration-ms="25" started-at="2019-12-07T22:18:08Z" finished-at="2019-12-07T22:18:08Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[5]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 5
	at com.ooad.ConsoleInput.findEmptyPosition(ConsoleInput.java:99)
	at com.ooad.ConsoleInput.enterLetter(ConsoleInput.java:20)
	at com.test.ConsoleInputTest.enterLetter(ConsoleInputTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterLetter -->
        <test-method status="PASS" signature="findEmptyPosition()[pri:0, instance:com.test.ConsoleInputTest@48eff760]" name="findEmptyPosition" duration-ms="8" started-at="2019-12-07T22:18:08Z" finished-at="2019-12-07T22:18:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findEmptyPosition -->
        <test-method status="PASS" signature="inEnteredLetters()[pri:0, instance:com.test.ConsoleInputTest@48eff760]" name="inEnteredLetters" duration-ms="1" started-at="2019-12-07T22:18:08Z" finished-at="2019-12-07T22:18:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inEnteredLetters -->
        <test-method status="PASS" signature="printWord()[pri:0, instance:com.test.ConsoleInputTest@48eff760]" name="printWord" duration-ms="3" started-at="2019-12-07T22:18:08Z" finished-at="2019-12-07T22:18:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- printWord -->
      </class> <!-- com.test.ConsoleInputTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
